version: '3.8'

services:
  zookeeper_t1:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: zookeeper_t1
    container_name: zookeeper_t1
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000

  kafka_t1:
    image: confluentinc/cp-kafka:5.5.0
    hostname: kafka_t1
    container_name: kafka_t1
    depends_on:
      - zookeeper_t1
    ports:
      - "9093:9093"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT  #без шифрования
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_t1:29092, PLAINTEXT_HOST://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_t1:2182
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "54321:5432"

#  kafka-manager:
#    image: hlebalbau/kafka-manager:stable
#    container_name: kafka-manager
#    depends_on:
#      - kafka_t1
#    ports:
#      - "9000:9000"
#    environment:
#      ZK_HOSTS: "zookeeper_t1:2182"
#      APPLICATION_SECRET: "randomsecret"
