spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/my_database
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

#
#docker:
#  container:
#    name: my_postgres_container
#    image: postgres:latest
#    ports:
#      - "54321:5432"
#    environment:
#      POSTGRES_DB: my_database
#      POSTGRES_USER: my_user
#      POSTGRES_PASSWORD: my_password